module netcdf_cxx_mod
    use iso_c_binding, only : c_char, c_null_char, c_null_ptr, c_int, c_ptr
    use f_c_string_t_mod, only : f_c_string_t
    use f_c_string_1D_t_mod, only : f_c_string_1D_t
    use netcdf_cxx_i_mod
    use netcdf, only : NF90_INT, NF90_INT64, NF90_REAL
    implicit none
    public

contains

    ! netcdfCreate:
    !   Creates a new NetCDF file or opens an existing file in a specified mode,
    !   using a Fortran string for the file path. This function wraps the
    !   `c_netcdfCreate` interface, which calls a C++ wrapper function that
    !   interacts with the NetCDF C++ API.
    !
    !   Arguments:
    !     - path (character(len=*), intent(in)): The file path as a Fortran string.
    !     - netcdfID (integer(c_int), intent(inout)): On input, it may contain an
    !       identifier to be updated; on output, it holds the file identifier
    !       for the created or opened NetCDF file.
    !
    !   Returns:
    !     - integer(c_int): A status code indicating success (0) or failure (non-zero).
    !
    !   Notes:
    !     - The `f_c_string_t` type is used internally to handle the conversion
    !       of the Fortran string `path` into a null-terminated C string (`c_path`).
    !     - The `c_netcdfCreate` function serves as an interface between Fortran
    !       and the C++ wrapper function, ensuring proper communication between
    !       the languages.
    function netcdfCreate(path, netcdfID)
        character(len = *), intent(in) :: path
        integer(c_int), intent(inout) :: netcdfID
        integer(c_int) :: netcdfCreate
        type(f_c_string_t) :: f_c_string_path
        type(c_ptr) :: c_path

        c_path = f_c_string_path%to_c(path)
        netcdfCreate = c_netcdfCreate(c_path, netcdfID)
    end function netcdfCreate

    ! netcdfClose:
    !   Closes a previously opened NetCDF file identified by its file identifier.
    !   This function wraps the `c_netcdfClose` interface, which calls a C++
    !   wrapper function to interact with the NetCDF C++ API.
    !
    !   Arguments:
    !     - netcdfID (integer(c_int), intent(in), value): The identifier of the
    !       NetCDF file to close.
    !
    !   Returns:
    !     - integer(c_int): A status code indicating success (0) or failure (non-zero).
    !
    !   Notes:
    !     - The `c_netcdfClose` function acts as an interface between Fortran and
    !       the C++ wrapper function, abstracting the complexity of C++ interactions.
    function netcdfClose(netcdfID)
        integer(c_int), value, intent(in) :: netcdfID
        integer(c_int) :: netcdfClose
        netcdfClose = c_netcdfClose(netcdfID)
    end function netcdfClose

    ! netcdfAddGroup:
    !   Adds a new group to a NetCDF file under a specified parent group.
    !   This function wraps the `c_netcdfAddGroup` interface, which calls a C++
    !   wrapper function that interacts with the NetCDF C++ API.
    !
    !   Arguments:
    !     - netcdfID (integer(c_int), intent(in), value):
    !       The identifier of the NetCDF file where the group will be added.
    !     - groupName (character(len=*), intent(in)):
    !       The name of the new group to be created within the specified parent group.
    !     - parentGroupName (character(len=*), intent(in), optional):
    !       The name of the parent group under which the new group will be added.
    !       If not provided, the new group will be created in the root group.
    !
    !   Returns:
    !     - integer(c_int): A status code indicating the outcome of the operation:
    !         - 0: Success.
    !         - Non-zero: Failure, with an error message generated by the underlying
    !           C++ API.
    !
    !   Notes:
    !     - The `f_c_string_t` type is used to convert the Fortran strings `groupName`
    !       and `parentGroupName` into null-terminated C strings.
    !     - If `parentGroupName` is not present, the `c_null_ptr` is passed to indicate
    !       that the group should be added to the root group.
    !     - This function ensures compatibility between Fortran and C++ for group
    !       creation, simplifying the user's workflow.
    !
    !   Example Usage:
    !   ```
    !   integer(c_int) :: netcdfID, status
    !   character(len=256) :: groupName, parentGroupName
    !   groupName = "new_group" // c_null_char
    !   parentGroupName = "existing_group" // c_null_char
    !
    !   status = netcdfAddGroup(netcdfID, groupName, parentGroupName)
    !   if (status /= 0) then
    !       ! Handle error
    !   endif
    !   ```
    function netcdfAddGroup(netcdfID, groupName, parentGroupName)
        integer(c_int), value, intent(in) :: netcdfID
        character(len = *), intent(in), optional :: parentGroupName
        character(len = *), intent(in) :: groupName
        integer(c_int) :: netcdfAddGroup
        type(c_ptr) :: c_parentGroupName
        type(c_ptr) :: c_groupName
        type(f_c_string_t) :: f_c_string_parentGroupName
        type(f_c_string_t) :: f_c_string_groupName

        if (present(parentGroupName)) then
            c_parentGroupName = f_c_string_parentGroupName%to_c(parentGroupName)
        else
            c_parentGroupName = c_null_ptr
        end if
        c_groupName = f_c_string_groupName%to_c(groupName)

        netcdfAddGroup = c_netcdfAddGroup(netcdfID, c_parentGroupName, c_groupName)
    end function netcdfAddGroup

    ! netcdfAddDim:
    !   Adds a new dimension to a NetCDF file, either in the root group or a specified group.
    !   This function provides a Fortran interface for adding dimensions, wrapping the
    !   lower-level `c_netcdfAddDim` binding to simplify usage in Fortran programs.
    !
    !   Arguments:
    !     - netcdfID (integer(c_int), intent(in), value):
    !       The identifier of the NetCDF file to which the dimension will be added.
    !     - dimName (character(len=*), intent(in)):
    !       The name of the new dimension to be created.
    !     - len (integer(c_int), intent(in), value):
    !       The length of the dimension. Use `NC_UNLIMITED` for unlimited dimensions.
    !     - groupName (character(len=*), intent(in), optional):
    !       The name of the group in which the dimension will be created. If not provided,
    !       the dimension will be added to the root group.
    !
    !   Returns:
    !     - integer(c_int): Status code indicating the result of the operation:
    !         - 0: Success.
    !         - Non-zero: Failure, with errors handled by the underlying C++ implementation.
    !
    !   Notes:
    !     - The function automatically handles the conversion of Fortran strings (`dimName`
    !       and `groupName`) to C-compatible null-terminated strings.
    !     - If `groupName` is not provided, the dimension is added to the root group by passing
    !       `c_null_ptr` to the underlying C binding.
    !
    !   Example Usage:
    !   ```
    !   integer(c_int) :: netcdfID, status
    !   character(len=256) :: dimName, groupName
    !   dimName = "time"
    !   groupName = "group1"
    !   status = netcdfAddDim(netcdfID, dimName, 100, groupName)
    !   if (status /= 0) then
    !       ! Handle error
    !   endif
    !   ```
    function netcdfAddDim(netcdfID, dimName, len, groupName)
        integer(c_int), value, intent(in) :: netcdfID
        character(len = *), intent(in) :: dimName
        integer(c_int), value, intent(in) :: len
        character(len = *), optional, intent(in) :: groupName
        integer(c_int) :: netcdfAddDim
        type(c_ptr) :: c_groupName
        type(c_ptr) :: c_dimName
        type(f_c_string_t) :: f_c_string_groupName
        type(f_c_string_t) :: f_c_string_dimName

        if (present(groupName)) then
            c_groupName = f_c_string_groupName%to_c(groupName)
        else
            c_groupName = c_null_ptr
        end if
        c_dimName = f_c_string_dimName%to_c(dimName)

        netcdfAddDim = c_netcdfAddDim(netcdfID, c_groupName, c_dimName, len)
    end function netcdfAddDim

    ! netcdfAddVar:
    !   Adds a new variable to a NetCDF file, specifying its name, type, dimensions, and target group.
    !   This function provides a Fortran interface for defining variables, wrapping the
    !   lower-level `c_netcdfAddVar` binding to simplify usage in Fortran programs.
    !
    !   Arguments:
    !     - netcdfID (integer(c_int), intent(in), value):
    !       The identifier of the NetCDF file to which the variable will be added.
    !     - varName (character(len=*), intent(in)):
    !       The name of the new variable to be created.
    !     - netcdfDataType (integer(c_int), intent(in), value):
    !       The data type of the variable, using NetCDF predefined constants (e.g., `NF90_INT`, `NF90_REAL`).
    !     - numDims (integer(c_int), intent(in), value):
    !       The number of dimensions associated with the variable.
    !     - dimNames (character(len=*), dimension(numDims), intent(in)):
    !       An array of dimension names that define the variable's shape.
    !     - groupName (character(len=*), optional, intent(in)):
    !       The name of the group in which the variable will be created. If not provided,
    !       the variable will be added to the root group.
    !
    !   Returns:
    !     - integer(c_int): Status code indicating the result of the operation:
    !         - 0: Success.
    !         - Non-zero: Failure, with errors handled by the underlying C++ implementation.
    !
    !   Notes:
    !     - The function automatically handles the conversion of Fortran strings (`varName`,
    !       `dimNames`, and `groupName`) to C-compatible null-terminated strings.
    !     - If `groupName` is not provided, the variable is added to the root group by passing
    !       `c_null_ptr` to the underlying C binding.
    function netcdfAddVar(netcdfID, varName, netcdfDataType, numDims, dimNames, groupName)
        integer(c_int), value, intent(in) :: netcdfID
        character(len = *), intent(in) :: varName
        integer(c_int), value, intent(in) :: netcdfDataType
        integer(c_int), value, intent(in) :: numDims
        character(len = *), dimension(numDims), intent(in) :: dimNames
        character(len = *), optional, intent(in) :: groupName
        integer(c_int) :: netcdfAddVar
        type(c_ptr) :: c_groupName
        type(c_ptr) :: c_varName
        type(c_ptr) :: c_dimNames
        type(f_c_string_t) :: f_c_string_groupName
        type(f_c_string_t) :: f_c_string_varName
        type(f_c_string_1D_t) :: f_c_string_1D_dimNames

        if (present(groupName)) then
            c_groupName = f_c_string_groupName%to_c(groupName)
        else
            c_groupName = c_null_ptr
        end if
        c_varName = f_c_string_varName%to_c(varName)
        c_dimNames = f_c_string_1D_dimNames%to_c(dimNames)
        netcdfAddVar = c_netcdfAddVar(netcdfID, c_groupName, c_varName, &
                netcdfDataType, numDims, c_dimNames)
    end function netcdfAddVar

    ! netcdfPutVar:
    !   Writes data to a variable in a NetCDF file. This function supports variables
    !   with different data types (e.g., integers, floats, strings) and allows writing
    !   data to variables in specific groups or the root group.
    !
    !   Arguments:
    !     - netcdfID (integer(c_int), intent(in), value):
    !       The identifier of the NetCDF file where the data will be written.
    !     - varName (character(len=*), intent(in)):
    !       The name of the variable to which data will be written.
    !     - data (class(*), dimension(:), intent(in)):
    !       The data to be written to the variable. Supported types include:
    !         - integer(c_int), integer(c_long), real(c_float), and character(len=*).
    !     - groupName (character(len=*), optional, intent(in)):
    !       The name of the group containing the variable. If not provided, the variable
    !       is assumed to be in the root group.
    !
    !   Returns:
    !     - integer(c_int): Status code indicating the result of the operation:
    !         - 0: Success.
    !         - Non-zero: Failure, with errors handled by the underlying C++ implementation.
    !
    !   Notes:
    !     - The function automatically handles data type conversions and memory allocation
    !       for transferring data between Fortran and the C++ NetCDF API.
    !     - For strings, `f_c_string_1D_t` is used to manage conversion of Fortran arrays
    !       to C-compatible null-terminated strings.
    function netcdfPutVar(netcdfID, varName, data, groupName)
        integer(c_int), value, intent(in) :: netcdfID
        character(len = *), intent(in) :: varName
        class(*), dimension(:), intent(in) :: data
        character(len = *), optional, intent(in) :: groupName
        integer(c_int) :: netcdfPutVar
        type(f_c_string_t) :: f_c_string_groupName
        type(f_c_string_t) :: f_c_string_varName
        type(c_ptr) :: c_groupName
        type(c_ptr) :: c_varName
        type(c_ptr) :: c_data
        type(f_c_string_1D_t) :: f_c_string_1D_data

        c_varName = f_c_string_varName%to_c(varName)

        select type (data)
        type is (integer(c_int))
            c_data = c_loc(data)
            netcdfPutVar = c_netcdfPutVarInt(netcdfID, c_groupName, &
                    c_varName, c_data)

        type is (integer(c_long))
            c_data = c_loc(data)
            netcdfPutVar = c_netcdfPutVarInt64(netcdfID, c_groupName, &
                    c_varName, c_data)

        type is (real(c_float))
            c_data = c_loc(data)
            netcdfPutVar = c_netcdfPutVarReal(netcdfID, c_groupName, &
                    c_varName, c_data)

        type is (character(len = *))
            c_data = f_c_string_1D_data%to_c(data)
            netcdfPutVar = c_netcdfPutVarString(netcdfID, c_groupName, &
                    c_varName, c_data)
        end select
    end function netcdfPutVar

end module netcdf_cxx_mod
