module netcdf_cxx_i_mod
    use iso_c_binding
    implicit none
    public



    interface
        ! c_netcdfCreate:
        !   Creates a new NetCDF file or opens an existing file in a specified mode.
        !   The file path must be passed as a C-compatible null-terminated string.
        !   The resulting file identifier is returned in `netcdfID` for further operations.
        !
        !   Arguments:
        !     - path (type(c_ptr), intent(in), value): A C pointer to a null-terminated
        !       string representing the file path.
        !     - netcdfID (integer(c_int), intent(out)): Receives the file identifier
        !       for the created or opened NetCDF file.
        !
        !   Returns:
        !     - integer(c_int): A status code indicating success (0) or failure (non-zero).
        function c_netcdfCreate(path, netcdfID) &
                bind(C, name = "netcdfCreate")
            import :: c_int
            import :: c_ptr
            type(c_ptr), value, intent(in) :: path
            integer(c_int), intent(out) :: netcdfID
            integer(c_int) :: c_netcdfCreate
        end function

        ! c_netcdfClose:
        !   Closes a previously opened NetCDF file identified by its file identifier.
        !
        !   Arguments:
        !     - netcdfID (integer(c_int), intent(in), value): The identifier of the
        !       NetCDF file to close.
        !
        !   Returns:
        !     - integer(c_int): A status code indicating success (0) or failure (non-zero).
        function c_netcdfClose(netcdfID) &
                bind(C, name = "netcdfClose")
            import :: c_int
            integer(c_int), value, intent(in) :: netcdfID
            integer(c_int) :: c_netcdfClose
        end function

        ! c_netcdfAddGroup:
        !   Adds a new group to a NetCDF file under a specified parent group.
        !   This function is a Fortran binding to the C++ implementation of group addition,
        !   leveraging the NetCDF C++ API for robust error handling and thread safety.
        !
        !   Arguments:
        !     - netcdfID (integer(c_int), intent(in), value):
        !       The identifier of the NetCDF file where the group will be added.
        !     - parentGroupName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the name of the parent
        !       group under which the new group will be created. If targeting the root
        !       group, this can be an empty string or the top-level group name.
        !     - groupName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the name of the new group
        !       to be added under the parent group.
        !
        !   Returns:
        !     - integer(c_int): A status code indicating the outcome of the operation:
        !         - 0: Success.
        !         - Non-zero: Failure, with an error message generated by the underlying
        !           C++ API.
        !
        !   Notes:
        !     - This function assumes `netcdfID` is valid and corresponds to an open NetCDF
        !       file managed by the internal file handling utilities.
        !     - The parent group must exist; otherwise, the operation will fail with an error.
        !     - Fortran clients must pass valid C pointers for `parentGroupName` and
        !       `groupName` to ensure compatibility with the underlying C++ implementation.
        !
        !   Example Usage:
        !   ```
        !   integer(c_int) :: netcdfID, status
        !   character(len=256) :: parentGroup, newGroup
        !   parentGroup = "parent_group_name" // c_null_char
        !   newGroup = "new_group_name" // c_null_char
        !   status = c_netcdfAddGroup(netcdfID, c_loc(parentGroup), c_loc(newGroup))
        !   if (status /= 0) then
        !       ! Handle error
        !   endif
        !   ```
        function c_netcdfAddGroup(&
                netcdfID, parentGroupName, groupName) &
                bind(C, name = "netcdfAddGroup")
            import :: c_int
            import :: c_ptr
            integer(c_int), value, intent(in) :: netcdfID
            type(c_ptr), value, intent(in) :: parentGroupName
            type(c_ptr), value, intent(in) :: groupName
            integer(c_int) :: c_netcdfAddGroup
        end function c_netcdfAddGroup

        ! c_netcdfAddDim:
        !   Adds a new dimension to a NetCDF file, either in the root group or a specified group.
        !   This function is a Fortran binding to the C++ implementation of `netcdfAddDim`, allowing
        !   seamless integration with the NetCDF C++ API for creating dimensions.
        !
        !   Arguments:
        !     - netcdfID (integer(c_int), intent(in), value):
        !       The identifier of the NetCDF file to which the dimension will be added.
        !     - groupName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the name of the group
        !       where the dimension will be created. If targeting the root group, pass `c_null_ptr`.
        !     - dimName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the name of the new dimension.
        !     - len (integer(c_int), intent(in), value):
        !       The length of the dimension. Use `NC_UNLIMITED` for unlimited dimensions.
        !
        !   Returns:
        !     - integer(c_int): Status code indicating the result of the operation:
        !         - 0: Success.
        !         - Non-zero: Failure, with errors handled by the underlying C++ implementation.
        !
        !   Notes:
        !     - The function assumes that `netcdfID` is valid and corresponds to an open NetCDF file.
        !     - Both `groupName` and `dimName` must be valid C pointers pointing to null-terminated strings.
        !     - Fortran developers should use appropriate utilities (e.g., `f_c_string_t`) to manage
        !       string conversions when calling this function.
        !
        !   Example Usage:
        !   ```
        !   integer(c_int) :: netcdfID, status
        !   type(f_c_string_t) :: f_groupName, f_dimName
        !   f_groupName%to_c("group1")
        !   f_dimName%to_c("time")
        !   status = c_netcdfAddDim(netcdfID, f_groupName%ptr, f_dimName%ptr, 100)
        !   if (status /= 0) then
        !       ! Handle error
        !   endif
        !   ```
        function c_netcdfAddDim(&
                netcdfID, groupName, dimName, len) &
                bind(C, name = "netcdfAddDim")
            import :: c_int
            import :: c_ptr
            integer(c_int), value, intent(in) :: netcdfID
            type(c_ptr), value, intent(in) :: groupName
            type(c_ptr), value, intent(in) :: dimName
            integer(c_int), value, intent(in) :: len
            integer(c_int) :: c_netcdfAddDim
        end function c_netcdfAddDim

        ! c_netcdfAddVar:
        !   Adds a new variable to a NetCDF file, specifying its name, type, and associated dimensions.
        !   This is a C binding for the NetCDF C++ API that allows variable creation.
        !
        !   Arguments:
        !     - netcdfID (integer(c_int), intent(in), value):
        !       The identifier of the NetCDF file where the variable will be created.
        !     - groupName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the group name. If `c_null_ptr`,
        !       the variable is added to the root group.
        !     - varName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the variable name.
        !     - netcdfDataType (integer(c_int), intent(in), value):
        !       The NetCDF data type of the variable (e.g., `NF90_INT`, `NF90_REAL`).
        !     - numDims (integer(c_int), intent(in), value):
        !       The number of dimensions associated with the variable.
        !     - dimNames (type(c_ptr), intent(in), value):
        !       A C pointer to an array of null-terminated strings representing the dimension names.
        !
        !   Returns:
        !     - integer(c_int): Status code indicating success (0) or failure (non-zero).
        !
        !   Notes:
        !     - This function assumes that `netcdfID` corresponds to a valid NetCDF file.
        !     - All strings must be null-terminated and passed as C pointers.
        function c_netcdfAddVar(&
                netcdfID, groupName, varName, netcdfDataType, numDims, dimNames) &
                bind(C, name = "netcdfAddVar")
            import :: c_int
            import :: c_ptr
            integer(c_int), value, intent(in) :: netcdfID
            type(c_ptr), value, intent(in) :: groupName
            type(c_ptr), value, intent(in) :: varName
            integer(c_int), value, intent(in) :: netcdfDataType
            integer(c_int), value, intent(in) :: numDims
            type(c_ptr), value, intent(in) :: dimNames
            integer(c_int) :: c_netcdfAddVar
        end function c_netcdfAddVar

        ! c_netcdfPutVarInt:
        !   Writes integer data to a NetCDF variable in the specified group or root group.
        !
        !   Arguments:
        !     - netcdfID (integer(c_int), intent(in), value):
        !       The identifier of the NetCDF file.
        !     - groupName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the group name. If `c_null_ptr`,
        !       the variable is assumed to be in the root group.
        !     - varName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the variable name.
        !     - data (type(c_ptr), intent(in), value):
        !       A C pointer to the array of integer data to be written.
        !
        !   Returns:
        !     - integer(c_int): Status code indicating success (0) or failure (non-zero).
        !
        !   Notes:
        !     - This function writes integer (`c_int`) data. Ensure the data array matches the variable's type.
        function c_netcdfPutVarInt(&
                netcdfID, groupName, varName, data) &
                bind(C, name = "netcdfPutVarInt")
            import :: c_int
            import :: c_ptr
            integer(c_int), value, intent(in) :: netcdfID
            type(c_ptr), value, intent(in) :: groupName
            type(c_ptr), value, intent(in) :: varName
            type(c_ptr), value, intent(in) :: data
            integer(c_int) :: c_netcdfPutVarInt
        end function c_netcdfPutVarInt

        ! c_netcdfPutVarInt64:
        !   Writes 64-bit integer data to a NetCDF variable in the specified group or root group.
        !
        !   Arguments:
        !     - netcdfID (integer(c_int), intent(in), value):
        !       The identifier of the NetCDF file.
        !     - groupName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the group name. If `c_null_ptr`,
        !       the variable is assumed to be in the root group.
        !     - varName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the variable name.
        !     - data (type(c_ptr), intent(in), value):
        !       A C pointer to the array of 64-bit integer data to be written.
        !
        !   Returns:
        !     - integer(c_int): Status code indicating success (0) or failure (non-zero).
        function c_netcdfPutVarInt64(&
                netcdfID, groupName, varName, data) &
                bind(C, name = "netcdfPutVarInt64")
            import :: c_int
            import :: c_ptr
            integer(c_int), value, intent(in) :: netcdfID
            type(c_ptr), value, intent(in) :: groupName
            type(c_ptr), value, intent(in) :: varName
            type(c_ptr), value, intent(in) :: data
            integer(c_int) :: c_netcdfPutVarInt64
        end function c_netcdfPutVarInt64

        ! c_netcdfPutVarReal:
        !   Writes real (floating-point) data to a NetCDF variable in the specified group or root group.
        !
        !   Arguments:
        !     - netcdfID (integer(c_int), intent(in), value):
        !       The identifier of the NetCDF file.
        !     - groupName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the group name. If `c_null_ptr`,
        !       the variable is assumed to be in the root group.
        !     - varName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the variable name.
        !     - data (type(c_ptr), intent(in), value):
        !       A C pointer to the array of real data to be written.
        !
        !   Returns:
        !     - integer(c_int): Status code indicating success (0) or failure (non-zero).
        function c_netcdfPutVarReal(&
                netcdfID, groupName, varName, data) &
                bind(C, name = "netcdfPutVarReal")
            import :: c_int
            import :: c_ptr
            integer(c_int), value, intent(in) :: netcdfID
            type(c_ptr), value, intent(in) :: groupName
            type(c_ptr), value, intent(in) :: varName
            type(c_ptr), value, intent(in) :: data
            integer(c_int) :: c_netcdfPutVarReal
        end function c_netcdfPutVarReal

        ! c_netcdfPutVarString:
        !   Writes string data to a NetCDF variable in the specified group or root group.
        !
        !   Arguments:
        !     - netcdfID (integer(c_int), intent(in), value):
        !       The identifier of the NetCDF file.
        !     - groupName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the group name. If `c_null_ptr`,
        !       the variable is assumed to be in the root group.
        !     - varName (type(c_ptr), intent(in), value):
        !       A C pointer to a null-terminated string specifying the variable name.
        !     - data (type(c_ptr), intent(in), value):
        !       A C pointer to the array of strings to be written.
        !
        !   Returns:
        !     - integer(c_int): Status code indicating success (0) or failure (non-zero).
        !
        !   Notes:
        !     - Ensure that the data array contains valid C-style null-terminated strings.
        function c_netcdfPutVarString(&
                netcdfID, groupName, varName, data) &
                bind(C, name = "netcdfPutVarString")
            import :: c_int
            import :: c_ptr
            integer(c_int), value, intent(in) :: netcdfID
            type(c_ptr), value, intent(in) :: groupName
            type(c_ptr), value, intent(in) :: varName
            type(c_ptr), value, intent(in) :: data
            integer(c_int) :: c_netcdfPutVarString
        end function c_netcdfPutVarString

    end interface

end module netcdf_cxx_i_mod
